const demoFarms = [
  {
    id: "1",
    farmName: "Green Haven",
    location: "Gulshan, Dhaka",
    size: "50 sqm",
    price: 1500,
    availability: true,
    vendorId: { farmName: "Green Haven" },
  },
  {
    id: "2",
    farmName: "Urban Roots",
    location: "Dhanmondi, Dhaka",
    size: "35 sqm",
    price: 1200,
    availability: true,
    vendorId: { farmName: "Urban Roots" },
  },
  {
    id: "3",
    farmName: "City Growers",
    location: "Banani, Dhaka",
    size: "60 sqm",
    price: 2000,
    availability: false,
    vendorId: { farmName: "City Growers" },
  },
  {
    id: "4",
    farmName: "Fresh Fields",
    location: "Mirpur, Dhaka",
    size: "45 sqm",
    price: 1300,
    availability: true,
    vendorId: { farmName: "Fresh Fields" },
  },
  {
    id: "5",
    farmName: "Skyline Farm",
    location: "Uttara, Dhaka",
    size: "70 sqm",
    price: 2500,
    availability: true,
    vendorId: { farmName: "Skyline Farm" },
  },
];

const demoProducts = [
  {
    id: "1",
    name: "Fresh Spinach",
    description: "Organic spinach grown بدون pesticides",
    price: 60,
    category: "Vegetables",
    availableQuantity: 25,
    certificationStatus: "approved",
    vendorId: { farmName: "Green Haven" },
  },
  {
    id: "2",
    name: "Cherry Tomatoes",
    description: "Sweet and juicy tomatoes, freshly harvested",
    price: 120,
    category: "Fruits",
    availableQuantity: 40,
    certificationStatus: "approved",
    vendorId: { farmName: "Urban Roots" },
  },
  {
    id: "3",
    name: "Basil Leaves",
    description: "Fresh aromatic basil for cooking",
    price: 80,
    category: "Herbs",
    availableQuantity: 15,
    vendorId: { farmName: "City Growers" },
  },
  {
    id: "4",
    name: "Carrot Seeds",
    description: "High quality seeds for home gardening",
    price: 50,
    category: "Seeds",
    availableQuantity: 100,
    vendorId: { farmName: "Fresh Fields" },
  },
  {
    id: "5",
    name: "Garden Shovel",
    description: "Durable tool for planting and digging",
    price: 350,
    category: "Tools",
    availableQuantity: 10,
    vendorId: { farmName: "Skyline Farm" },
  },
  {
    id: "6",
    name: "Organic Broccoli",
    description: "Healthy green broccoli مباشرة من المزرعة",
    price: 140,
    category: "Organic",
    availableQuantity: 18,
    certificationStatus: "approved",
    vendorId: { farmName: "Green Haven" },
  },
  {
    id: "7",
    name: "Potatoes",
    description: "Fresh farm potatoes, great for cooking",
    price: 45,
    category: "Vegetables",
    availableQuantity: 0,
    vendorId: { farmName: "Urban Roots" },
  },
  {
    id: "8",
    name: "Strawberries",
    description: "Sweet seasonal strawberries",
    price: 200,
    category: "Fruits",
    availableQuantity: 12,
    certificationStatus: "approved",
    vendorId: { farmName: "City Growers" },
  },
];

const demoPlants = [
  {
    id: "1",
    name: "Cherry Tomato",
    species: "Solanum lycopersicum",
    health: 85,
    stage: "Flowering",
    wateringSchedule: "Every 2 days",
    notes: "Growing بسرعة and looks healthy",
    plantedDate: "2026-03-20",
  },
  {
    id: "2",
    name: "Spinach",
    species: "Spinacia oleracea",
    health: 65,
    stage: "Vegetative",
    wateringSchedule: "Daily",
    notes: "Leaves slightly yellowing",
    plantedDate: "2026-04-01",
  },
  {
    id: "3",
    name: "Basil",
    species: "Ocimum basilicum",
    health: 90,
    stage: "Harvest",
    wateringSchedule: "Every 2 days",
    notes: "Ready for harvesting 🌿",
    plantedDate: "2026-02-15",
  },
  {
    id: "4",
    name: "Carrot",
    species: "Daucus carota",
    health: 40,
    stage: "Sprout",
    wateringSchedule: "Every 3 days",
    notes: "Needs more sunlight",
    plantedDate: "2026-04-10",
  },
  {
    id: "5",
    name: "Mint",
    species: "Mentha",
    health: 30,
    stage: "Vegetative",
    wateringSchedule: "Daily",
    notes: "Overwatered ⚠️",
    plantedDate: "2026-03-28",
  },
];

const demoPosts = [
  {
    id: "1",
    postContent: "My tomato plants are flowering! Any tips for better yield? 🍅",
    createdAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    userId: { id: "u1", name: "Rahim Ahmed", role: "Member" },
  },
  {
    id: "2",
    postContent: "Tip: Use compost weekly for healthier soil 🌱",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    userId: { id: "u2", name: "Fatima Noor", role: "Vendor" },
  },
  {
    id: "3",
    postContent: "Anyone growing basil indoors? Mine is drying out 😅",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    userId: { id: "u3", name: "Karim Ali", role: "Member" },
  },
  {
    id: "4",
    postContent: "Harvested my first spinach batch today! 🥬",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    userId: { id: "u1", name: "Rahim Ahmed", role: "Member" },
  },
  {
    id: "5",
    postContent: "Best natural pesticide for rooftop gardens?",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
    userId: { id: "u4", name: "Nusrat Jahan", role: "Member" },
  },
];

const mockOrders = [
  {
    id: "ORD123456",
    produceId: { name: "Fresh Tomatoes" },
    vendorId: { farmName: "Green Valley Farm" },
    orderDate: "2026-04-15",
    status: "pending",
  },
  {
    id: "ORD123457",
    produceId: { name: "Organic Potatoes" },
    vendorId: { farmName: "Sunrise Agro" },
    orderDate: "2026-04-14",
    status: "confirmed",
  },
  {
    id: "ORD123458",
    produceId: { name: "Carrots" },
    vendorId: { farmName: "Farm Fresh Ltd." },
    orderDate: "2026-04-13",
    status: "delivered",
  },
  {
    id: "ORD123459",
    produceId: { name: "Spinach" },
    vendorId: { farmName: "Healthy Greens" },
    orderDate: "2026-04-12",
    status: "cancelled",
  },
];

export { demoFarms, demoProducts, demoPlants, demoPosts, mockOrders };

export default demoFarms;